ALTER TABLE users
    ADD COLUMN bio TEXT NOT NULL DEFAULT '',
    ADD COLUMN avatar_url TEXT NOT NULL DEFAULT '',
    ADD COLUMN phone TEXT NOT NULL DEFAULT '',
    ADD COLUMN locale TEXT NOT NULL DEFAULT 'en',
    ADD COLUMN timezone TEXT NOT NULL DEFAULT 'UTC';
